### ISSUE TITLE
Wording problem in Debugging with Pry module

### ISSUE THREAD

**Issue by lqf2b8** [learn-co-curriculum/pry-readme#14]
In the Debugging with Pry module under the What is Pry paragraph the following sentence could use some rewording. "Any code you want to play with in IRB, you can to write in IRB or copy and paste into IRB. Pry, on the other hand, is like a REPL that you can inject into your program." I am guessing it should read "you have to write" instead of "you can to write" Obviously this is nothing major. Let me know if you want me to stop sending you these minor wording issues and I will stop. Don't want to get the reputation for being "that" guy.

thanks

**Comment by AnnJohn** [comment]
@lqf2b8 Thanks and keep sending these issues! Fixed the typo.
