### ISSUE TITLE
Pry Video

### ISSUE THREAD

**Issue by iandevivi** [learn-co-curriculum/pry-readme#27]
I'm not sure if it's because the video is 4+ years old or if I haven't set up pry correctly, but this is an extremely frustrating video to attempt to follow along with.  The speed, plus the differences between what is on video versus what I have are just too much.  Some new pry content, especially at a pace that the beginner can follow along with, would be very helpful.

**Comment by AnnJohn** [comment]
thanks @iandevivi. A couple of people have raised this issue so we're going to go ahead and remove this resource.
