### ISSUE TITLE
I am getting the following message when running ruby lib/pry_is_awesome.rb

### ISSUE THREAD

**Issue by albertoegomez** [learn-co-curriculum/pry-readme#29]
Hi,

I cannot complete this lesson or run PRY for due to the following error message that appears. Can you provide assistance on how to next proceed? Thanks. 

    14:   # Unfortunately doesn't work in 1.9.2 because of                      
    15:   # http://redmine.ruby-lang.org/issues/3921. Works fine in 1.8.7 and 1.
9.3.                                                                            
    16:   stop unless RUBY_VERSION == '1.9.2'                                   
    17:                                                                         
    18:   return_value = nil                                                    
    19:   command = catch(:breakout_nav) do      # Coordinates with PryNav::Comm
ands                                                                            
    20:     return_value = yield                                                
 => 21:     {}    # Nothing thrown == no navigational command                   
    22:   end                                                                   
    23:                                                                         
    24:   # Adjust tracer based on command                                      
    25:   if process_command(command)                                           
    26:     start                                                               
    27:   else                                                                  
    28:     stop if RUBY_VERSION == '1.9.2'

**Comment by AnnJohn** [comment]
hi @albertoegomez since this looks like it's an issue specific to you. Can you please use the Ask a Question tool and someone from our team will get back to you one on one? Thanks!
