### ISSUE TITLE
Pry Error (currently solved by uninstalling pry-byebug gem)

### ISSUE THREAD

**Issue by orchardtree** [learn-co-curriculum/pry-readme#30]
Hi, there may be a better way to solve this, but I solved the error (screenshot below) by uninstalling the pry-byebug gem. I was then able to use Pry successfully on various Learn exercises, and I continue to be able to use pry without issue (so this is not an emergency). Just wanted to let you know as an fyi and to see if you have any alternate superior recommendations for resolving the error. 

Solution source:
http://stackoverflow.com/questions/35531651/ruby-pry-installation-gives-strange-results

If you have any questions or need any additional info, please let me know.

Thanks,
Jesse

![pry error solved by uninstalling bye_bug](https://cloud.githubusercontent.com/assets/18484128/17643903/b798bba6-6145-11e6-981a-53146a1ca96e.PNG)

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this up. We are currently reviewing if there are any issues between pry and pry-nav. If so we will update the README.

As always, thanks for contributing! 💙
