### ISSUE TITLE
pry giving issues

### ISSUE THREAD

**Issue by mahdiASC** [learn-co-curriculum/pry-readme#32]
After installing and trying to run pry as instructed, I ran into an error with one of the pry gems, pry-nav.

`...tracer.rb @line 21 PryNav::Tracer#run`

Solution was to uninstall that gem

`gem uninstall pry-nav`

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this up. We are currently reviewing if there are any issues between pry and pry-nav. If so we will update the README.

As always, thanks for contributing! 💙
