### ISSUE TITLE
Confusing for IDE users

### ISSUE THREAD

**Issue by FreeBreadsticks** [learn-co-curriculum/pry-readme#36]
`Fork and clone this repository.`

`Install Pry on your computer by navigating to your home directory (cd ~ in your terminal) and execute gem install pry.`

`Now that pry is installed, navigate back to the lab debugging-with-pry and look at the code in lib/pry_is_awesome.rb`

These instructions get a lot of IDE users confused and going to their local terminal. Please give instructions on how to handle this in the IDE.

**Comment by sgharms** [comment]
Thanks for the suggestion. Change made!
