### ISSUE TITLE
Clarify-Spacing

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/pry-readme#37]
This isn't an actual typing but if working on a smaller screen device and/or not too familiar with installations, it's possible to misinterpret the `cd` on the instructions with `cd`2 .   Typing the latter will get some sort of bash error.  It may not be immediately clear that the 2 is the 2nd step in the instructions and not a part of the changing of the directory cd command.  Minor point, but it lead me to a Tech Coach nicely telling me that.  Ahem.

"Instructions Part I
1. Ensure that you're in the project "root" directory by issuing `cd` 2. Verify that 'pry' is installed: `gem list pry`: you should see something like `pry (0.11.3)`. The LearnIDE already has PRY installed."

**Comment by sgharms** [comment]
Good call. We've hard line-broken the line in question. Should be fixed.
