### ISSUE TITLE
I think I found a mistake.

### ISSUE THREAD

**Issue by arthurysong** [learn-co-curriculum/pry-readme#39]
Before we run 
ruby lib/pry_is_awesome.rb

instructions in part 1 say:
1. Ensure that you're in the project "root" directory by issuing `cd` . 2. Verify that 'pry' is installed: `gem list pry`: you should see something like `pry (0.11.3)`. The LearnIDE already has PRY installed.

If i run 'cd' like the instructions say it takes me to '~', and then if I try to run 'ruby lib/pry_is_awesome.rb', I get error:
Traceback (most recent call last):
ruby: No such file or directory -- lib/pry_is_awesome.rb (LoadError)

I have to fix this by first running 'cd debugging-with-pry-online-web-sp-000'
Then I can successfully run 'ruby lib/pry_is_awesome.rb'

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
