### ISSUE TITLE
Pronoun use is confusing

### ISSUE THREAD

**Issue by operacyloop** [learn-co-curriculum/pry-readme#40]
In the lesson it states the following: 

_In this repository that you've forked and cloned down onto your computer, you'll see a spec folder containing a file pry_debugging_spec.rb. This is a test for the file lib/pry_debugging.rb.

In that file, we have a broken method. Run learn to see the failing test._

The word **_that_** (the second word in the last line above) could refer to pry_debugging_spec.rb or lib/pry_debugging.rb, and is confusing to the new user.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
