### ISSUE TITLE
Pry Documentation link broken

### ISSUE THREAD

**Issue by imcarissa** [learn-co-curriculum/pry-readme#50]
The link provided below at the end of the lesson leads to a 404 error.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the correction may not appear on the lesson page right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

Thank you for contributing! 💙
